services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: appdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:  # simple DB UI in browser
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app          # live-reload on code changes
    environment:
      DATABASE_URL: postgresql+asyncpg://app:devpass@db:5432/appdb
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FAKE_LLM: "1"

    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy


volumes:
  pgdata:

