"""fix sqlite compatibility

Revision ID: eaa3e8aab224
Revises: 5eb3735cb86e
Create Date: 2025-10-01 16:17:48.836844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa3e8aab224'
down_revision: Union[str, None] = '5eb3735cb86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
